env:
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - ".eslintrc.yml"
rules:
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/ban-ts-comment": "warn"
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 2
