env:
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "node_modules"
  - "dist"
  - ".turbo"
  - "deploy"
  - "configs"
rules:
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "warn"
  "@typescript-eslint/ban-ts-comment": "warn"
  "@typescript-eslint/no-unused-vars": "warn"
  "@typescript-eslint/no-empty-function": "warn"
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-console: 2
