version: "3.8"

services:
    hello-service:
        image: mjet-hello-service
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - mjet-net
    api-gateway:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "3000:3000"
        networks:
            - mjet-net
networks:
    mjet-net:
