version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # ------------------------------------------------ #
      # [Aws sam]
      # ------------------------------------------------ #
      - npm i turbo
      - npm ci
      - sam validate -t deploy/aws/sam/template.yaml --region=$AWS_REGION
  build:
    commands:
      # ------------------------------------------------ #
      # [Aws sam]
      # ------------------------------------------------ #
      - npm run build
      - S3_BUCKET="BUCKET-NAME"
      - TEMPLATE_PARAMETERS_FILE_PATH=deploy/aws/sam/template-parameters/${ENVIRONMENT_CLASS}-parameters.sam.json
      - TEMPLATE_PARAMS=$(npm run ts deploy/aws/scripts/print-formatted-template-parameters.ts $TEMPLATE_PARAMETERS_FILE_PATH)
      - sam deploy \
        --stack-name $STACK_NAME \
        --region=$AWS_REGION \
        --s3-bucket=$S3_BUCKET \
        --capabilities=CAPABILITY_IAM \
        --parameter-overrides $TEMPLATE_PARAMS \
        --no-fail-on-empty-changeset
