name: Build Core and CLI

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    build-cli:
        runs-on: self-hosted-x64
        container:
            image: ubuntu:latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm ci
            - name: Build CLI
              run: npm run build:cli

    build-core:
        runs-on: self-hosted-x64
        container:
            image: ubuntu:latest
        defaults:
            run:
                working-directory: ./core
        steps:
            - uses: actions/checkout@v4
            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Build Core
              run: npm run build
